#ifndef CONSTANTS
#define CONSTANTS

// ADDRESS RELATED CONSTANTS
#define PORT "58104"

// SYSTEM SPECIFIC CONSTANTS
#define MAX_JPG_SIZE 10000000

#define COMMAND_WORD_SIZE 3
#define UID_SIZE 6
#define PASSWORD_SIZE 8
#define ASSET_NAME_SIZE 10
#define START_VALUE_SIZE 6
#define TIMEACTIVE_SIZE 5
#define FILE_NAME_SIZE 24
#define FILE_SIZE_SIZE 8
#define MAX_DIGITS 3

// DEFAULT CONSTANTS
#define BUFFER_SIZE 128
#define IMAGE_BUFFER_SIZE 2048
#define UDP_BUFFER_SIZE 6010

#endif